# Generated by Django 5.1.2 on 2024-11-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_main',
            name='role',
            field=models.CharField(choices=[('learner', 'Learner'), ('instructor', 'Instructor'), ('admin', 'Admin')], default='learner', max_length=20),
        ),
    ]
