# Generated by Django 5.1.2 on 2024-11-26 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_instructor', '0002_coursefeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursefeedback',
            name='score',
        ),
    ]
