# Generated by Django 5.1.2 on 2024-11-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_instructor', '0003_remove_coursefeedback_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursefeedback',
            name='audio_quality',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coursefeedback',
            name='course_content',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coursefeedback',
            name='teaching_method',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coursefeedback',
            name='video_quality',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
