# Generated by Django 5.1.2 on 2024-11-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_instructor', '0004_alter_coursefeedback_audio_quality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
